#!/usr/bin/python3
''' this is a collect of functions to generate the dummy data'''
import random

def getdummyenzyme():
	enzyme=["ABC","DEF","CGI"]
	return enzyme    
def getdummy_entry(name):
	i=int(random.uniform(1, 26))
	translation= "ERENEVISSAELRLFREQVDQGPDWERGFHRINIYEVMKPPAEVVPGHLITRLLDTRLVHHNVTRWETFDVSPAVLRWTREKQPNYGLAIEVTHLHQTRTHQGQHVRISRSLPQGSGNWAQLRPLLVTFGHDGRGHALTRRRRAKRSPKHHSQRARKKNKNCRRHSLYVDFSDVGWNDWIVAPPGYQAFYCHGDCPFPLADHLNSTNHAIVQTLVNSVNSSIPKACCVPTELSAISMLYLDEYDKV"
	DNA="GGAGGGGCCGCCGGGGAAGAGGAGGAGGAAGGAAAGAAAGAAAGCGAGGGAGGGAAAGAGGAGGAAGGAAGATGCGAGAAGGCAGAGGAGGAGGGAGGGAGGGAAGGAGCGCGGAGCCCGGCCCGGAAGCTAGGTGAGTGTGGCATCCGAGCTGAGGGACGCGAGCCTGAGACGCCGCTGCTGCTCCGGCTGAGTATCTAGCTTGTCTCCCCGATGGGATTCCCGTCCAAGCTATCTCGAGCCTGCAGCGCCACAGTCCCCGGCCCTCGCCCAGGTTCACTGCAACCGTTCAGAGGTCCCCAGGAGCTGCTGCTGGCGAGCCCGCTACTGCAGGGACCTATGGAGCCATTCCGTAGTGCCATCCCGAGCAACGCACTGCTGCAGCTTCCCTGAGCCTTTCCAGCAAGTTTGTTCAAGATTGGCTGTCAAGAATCATGGACTGTTATTATATGCCTTGTTTTCTGTCAAGACACCATGATTCCTGGTAACCGAATGCTGATGGTCGTTTTATTATGCCAAGTCCTGCTAGGAGGCGCGAGCCATGCTAGTTTGATACCTGAGACGGGGAAGAAAAAAGTCGCCGAGATTCAGGGCCACGCGGGAGGACGCCGCTCAGGGCAGAGCCATGAGCTCCTGCGGGACTTCGAGGCGACACTTCTGCAGATGTTTGGGCTGCGCCGCCGCCCGCAGCCTAGCAAGA"  
	items = dict( id=name, p_name=chr(97+i)+"_object", ga= chr(97+i)+str(i*1000), location = "unkown", DNA=DNA, Protein = translation )
	return items
def getdummy(n):
	items=[]
	for i in range(0,n):
		x = i -26 *int(i/26) if i > 26 else i
		insert = dict( id=1000+i, p_name=chr(97+i)+"_object", ga= chr(97+i)+str(i*1000), location = "unkown" )
		items.append(insert)
	return items