#!/usr/bin/python
#overall codon usage frequency

#get chromosome frequency
#calculate codon usage frequency


#connect to database
import myseql.connector

dbname   = "biodb"
dbhost   = "hope"
dbuser   = "cc001"   
dbpass   = "#########"   

sql_DNA = "SELECT DNA_sequence FROM sc001.Sequence"
#open database connection
connection = mysql.connector.connect (host=hope, user=cc001, db=biodb)
#prepare cursor
cursor = connection.cursor()
#SQL query
DNA= cursor.execute(sql_DNA)

# fetch all of the amino acid sequence
data_seq = cursor.fetchall ()

#transcribe DNA sequence


